<?php
/**
 * @file
 * Code for the Theme Settings feature.
 */

include_once 'dugto_theme_settings.features.inc';

/**
 * Implements hook_install_postinstall().
 *
 * This is a custom_config hook.
 */
function dugto_theme_settings_install_postinstall() {
  // Theme settings should be captured by strongrm, but just in case
  // they're not... let's set the default theme.
  variable_set('theme_default', 'dugto');
}
